version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

handlers:
  info_file_handler:
      class: logging.handlers.TimedRotatingFileHandler
      level: INFO
      formatter: simple
      filename: ../logs/info.log
      interval: 1
      when: D
      backupCount: 20
      encoding: utf8
  error_file_handler:
      class: logging.handlers.TimedRotatingFileHandler
      level: ERROR
      formatter: simple
      filename: ../logs/error.log
      interval: 1
      when: D
      backupCount: 20
      encoding: utf8

root:
  level: DEBUG
  handlers: [info_file_handler, error_file_handler]
